#! /usr/bin/env python

import logging
import os
import platform

from lab.calls.call import Call
from lab import tools

tools.configure_logging()

logging.info(f"node: {platform.node()}")

run_log = open("run.log", "w")
run_err = open("run.err", "w", buffering=1)  # line buffering
redirects = {"stdout": run_log, "stderr": run_err}

# Make sure we're in the run directory.
os.chdir(os.path.dirname(os.path.abspath(__file__)))

Call(['--translate-options', '--grounding-action-queue-ordering', 'fifo', '--hard-rules', 'hashset', '/Users/andreasravnholt/Universitet/5semester/P5-projekt/Popperscript/popper-output.txt', '--termination-condition', 'goal-relaxed-reachable', 'min-number', '745', '--search-options', '--search', 'eager_greedy([ff])'], hard_stderr_limit=10240, hard_stdout_limit=10240, memory_limit=2048, name='run-planner', soft_stderr_limit=64, soft_stdout_limit=1024, time_limit=1800, **redirects).wait()

Call(['/Library/Frameworks/Python.framework/Versions/3.8/bin/python3', '../../fast-downward.py'], hard_stderr_limit=10240, hard_stdout_limit=10240, memory_limit=None, name='fast_downward', soft_stderr_limit=64, soft_stdout_limit=1024, time_limit=None, **redirects).wait()


for f in [run_log, run_err]:
    f.close()
    if os.path.getsize(f.name) == 0:
        os.remove(f.name)
